language:
  - node_js

node_js:
  - "5.12"
  - "4.4"
  - "iojs"
  - "0.12"

os:
  - linux
  - osx

cache:
  bundler: true
  directories:
  - node_modules

sudo: false

matrix:
  fast_finish: true
  allow_failures:
  - os: osx

script:
  # Run test script, depending on istanbul install
  - "test ! -z $(npm -ps ls istanbul) || npm test"
  - "test   -z $(npm -ps ls istanbul) || npm run-script test-ci"

#after_script:
#  - "test -e ./coverage/lcov.info && npm install coveralls@2.10.0 && cat ./coverage/lcov.info | coveralls"


# Example
# https://github.com/octoblu/gateblu-forever/blob/master/.travis.yml
# https://github.com/travis-ci/travis-ci/issues/2311